In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("products.csv")

In [3]:
df.head(5)

,index,Category,brand,model,colour,product description,price in INR,rating,review
0,0.0,Electronics,Samsung,Galaxy S24 Ultra,Phantom Black,The Samsung Galaxy S24 Ultra is a high-perform...,129999,4.7,Extremely satisfied with the purchase! The cam...
1,1.0,Electronics,Samsung,Galaxy S24 Plus,Titanium Gray,The Samsung Galaxy S24 Plus is a high-performa...,109999,4.4,Blazing fast performance for daily multitaskin...
2,2.0,Electronics,Samsung,Galaxy S24,Natural Titanium,The Samsung Galaxy S24 is a high-performance f...,79999,3.9,Great value for money smartphone in this price...
3,3.0,Electronics,Apple,iPhone 15 Pro Max,Oasis Green,The Apple iPhone 15 Pro Max is a high-performa...,179900,4.8,The build quality feels high-end and comfortab...
4,4.0,Electronics,Apple,iPhone 15 Pro,Midnight Blue,The Apple iPhone 15 Pro is a high-performance ...,144900,4.5,Incredible display clarity and high refresh ra...

In [4]:
df.drop(columns=["review","index"], inplace=True)

In [5]:
df.head(5)

,Category,brand,model,colour,product description,price in INR,rating
0,Electronics,Samsung,Galaxy S24 Ultra,Phantom Black,The Samsung Galaxy S24 Ultra is a high-perform...,129999,4.7
1,Electronics,Samsung,Galaxy S24 Plus,Titanium Gray,The Samsung Galaxy S24 Plus is a high-performa...,109999,4.4
2,Electronics,Samsung,Galaxy S24,Natural Titanium,The Samsung Galaxy S24 is a high-performance f...,79999,3.9
3,Electronics,Apple,iPhone 15 Pro Max,Oasis Green,The Apple iPhone 15 Pro Max is a high-performa...,179900,4.8
4,Electronics,Apple,iPhone 15 Pro,Midnight Blue,The Apple iPhone 15 Pro is a high-performance ...,144900,4.5

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Category             1000 non-null   str
 1   brand                1000 non-null   str
 2   model                1000 non-null   str
 3   colour               1000 non-null   str
 4   product description  1000 non-null   str
 5   price in INR         1000 non-null   int64
 6   rating               1000 non-null   float64
dtypes: float64(1), int64(1), str(5)
memory usage: 54.8 KB

In [7]:
print(df.isnull().sum())

Category               0
brand                  0
model                  0
colour                 0
product description    0
price in INR           0
rating                 0
dtype: int64

In [8]:
print(df.duplicated().sum())

0

In [9]:
print(df["brand"].value_counts())

brand
Samsung     165
Apple        84
OnePlus      82
Motorola     81
Realme       80
Vivo         61
iQOO         61
Nothing      60
POCO         60
Redmi        60
Google       42
Tecno        42
ASUS         42
Xiaomi       40
Honor        40
Name: count, dtype: int64

In [10]:
print(df["model"].value_counts())

model
12 5G                                        24
Phone                                        24
Galaxy S24 Ultra                             12
Galaxy S24 Plus                              12
Galaxy S24                                   12
                                             ..
iPhone 15 Special Edition Variant #2407       1
Pixel 8 Pro Special Edition Variant #2408     1
Pixel 8a Special Edition Variant #2409        1
12 5G Special Edition Variant #2410           1
12R 5G Special Edition Variant #2411          1
Name: count, Length: 459, dtype: int64

In [11]:
print(df["rating"].value_counts().sort_index())

rating
3.9     39
4.0     62
4.1     66
4.2     44
4.3     62
4.4    465
4.5     56
4.6     41
4.7     61
4.8     52
4.9     52
Name: count, dtype: int64

In [12]:
print(df["price in INR"].describe())

count      1000.000000
mean      62967.350000
std       40818.858904
min       15999.000000
25%       31999.000000
50%       44999.000000
75%       90123.250000
max      199900.000000
Name: price in INR, dtype: float64

In [13]:
def data_converter(df,new_name="output"):
    # Convert to JSON
    print("CSV converted to JSON successfully!")
    return df.to_json(f"{new_name}.json", orient="records", indent=4)

In [14]:
data_converter(df[:500], "products_500")

CSV converted to JSON successfully!